{
  "name": "HGLaborLobby",
  "author": "bluefireoly",
  "version": "1.0.0",

  "main": "net.axay.hglaborlobby.main.InternalMainClass",
  "api-version": "1.16",

  "depend": ["LuckPerms"],

  "commands": {
    "vpn": {
      "description": "Toggle the vpn protection."
    },
    "spawn": {
      "description": "Teleportiert dich zum Spawn."
    },
    "admingui": {
      "description": "Öffnet das Admin GUI."
    },
    "damage": {
      description: "Stellt deinen Damager Schaden ein (in halben Herzen)"
    },
    "randomfirework": {
      description: "Du bekommst ein random Firework"
    },
    "formatting": {
      "description": "Zeigt dir an, welche Formatierungsoptionen du hast"
    }
  }
}
